// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	trending "github.com/slory7/angulargo/src/proto/trending"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0xc8, 0xd4,
	0x4f, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0x12,
	0x2f, 0x29, 0x4a, 0xcd, 0x4b, 0xc9, 0xcc, 0x4b, 0xd7, 0x87, 0x31, 0x20, 0xb2, 0x46, 0xa1, 0x5c,
	0xdc, 0x21, 0x50, 0x91, 0xe0, 0xa2, 0x32, 0x21, 0x37, 0x2e, 0x41, 0xf7, 0xd4, 0x12, 0xf7, 0xcc,
	0x92, 0x8c, 0xd2, 0x24, 0x98, 0xb8, 0x90, 0xa0, 0x1e, 0x5c, 0x53, 0x50, 0x6a, 0x61, 0x69, 0x6a,
	0x71, 0x89, 0x94, 0x0c, 0x42, 0x08, 0x55, 0xb1, 0x67, 0x5e, 0x5a, 0xbe, 0x12, 0x83, 0x93, 0x76,
	0x94, 0x66, 0x3a, 0x58, 0x5c, 0x2f, 0x39, 0x3f, 0x57, 0xbf, 0x38, 0x27, 0xbf, 0xa8, 0xd2, 0x5c,
	0x3f, 0x31, 0x2f, 0xbd, 0x34, 0x27, 0xb1, 0x28, 0x3d, 0x5f, 0xbf, 0xb8, 0x28, 0x59, 0x1f, 0x6c,
	0x3f, 0xc8, 0x9d, 0x49, 0x6c, 0x60, 0xa6, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x64, 0x6a,
	0x1c, 0xb9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrendingSrvClient is the client API for TrendingSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrendingSrvClient interface {
	GetGithubTrending(ctx context.Context, in *trending.Request, opts ...grpc.CallOption) (*trending.GithubTrendingInfo, error)
}

type trendingSrvClient struct {
	cc *grpc.ClientConn
}

func NewTrendingSrvClient(cc *grpc.ClientConn) TrendingSrvClient {
	return &trendingSrvClient{cc}
}

func (c *trendingSrvClient) GetGithubTrending(ctx context.Context, in *trending.Request, opts ...grpc.CallOption) (*trending.GithubTrendingInfo, error) {
	out := new(trending.GithubTrendingInfo)
	err := c.cc.Invoke(ctx, "/api.TrendingSrv/GetGithubTrending", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrendingSrvServer is the server API for TrendingSrv service.
type TrendingSrvServer interface {
	GetGithubTrending(context.Context, *trending.Request) (*trending.GithubTrendingInfo, error)
}

func RegisterTrendingSrvServer(s *grpc.Server, srv TrendingSrvServer) {
	s.RegisterService(&_TrendingSrv_serviceDesc, srv)
}

func _TrendingSrv_GetGithubTrending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(trending.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrendingSrvServer).GetGithubTrending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TrendingSrv/GetGithubTrending",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrendingSrvServer).GetGithubTrending(ctx, req.(*trending.Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrendingSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.TrendingSrv",
	HandlerType: (*TrendingSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGithubTrending",
			Handler:    _TrendingSrv_GetGithubTrending_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
