// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gather/gather.proto

package gather

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	BaseUrl              string            `protobuf:"bytes,1,opt,name=baseUrl,proto3" json:"baseUrl,omitempty"`
	RelativeUrl          string            `protobuf:"bytes,2,opt,name=relativeUrl,proto3" json:"relativeUrl,omitempty"`
	UrlParams            map[string]string `protobuf:"bytes,3,rep,name=urlParams,proto3" json:"urlParams,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Headers              map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContentType          string            `protobuf:"bytes,5,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Method               string            `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	PostData             string            `protobuf:"bytes,7,opt,name=postData,proto3" json:"postData,omitempty"`
	TimeOut              int32             `protobuf:"varint,8,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_766f0404ffec83b8, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetBaseUrl() string {
	if m != nil {
		return m.BaseUrl
	}
	return ""
}

func (m *Request) GetRelativeUrl() string {
	if m != nil {
		return m.RelativeUrl
	}
	return ""
}

func (m *Request) GetUrlParams() map[string]string {
	if m != nil {
		return m.UrlParams
	}
	return nil
}

func (m *Request) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPostData() string {
	if m != nil {
		return m.PostData
	}
	return ""
}

func (m *Request) GetTimeOut() int32 {
	if m != nil {
		return m.TimeOut
	}
	return 0
}

type Result struct {
	Content              string   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_766f0404ffec83b8, []int{1}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "gather.Request")
	proto.RegisterMapType((map[string]string)(nil), "gather.Request.HeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "gather.Request.UrlParamsEntry")
	proto.RegisterType((*Result)(nil), "gather.Result")
}

func init() { proto.RegisterFile("gather/gather.proto", fileDescriptor_766f0404ffec83b8) }

var fileDescriptor_766f0404ffec83b8 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0x71, 0xbc, 0xb1, 0x13, 0x65, 0xc9, 0x2e, 0xda, 0xa5, 0x08, 0x53, 0x8a, 0xc9, 0x29,
	0x87, 0x62, 0xd3, 0x14, 0xda, 0x92, 0xe6, 0xd4, 0x3f, 0x24, 0xb7, 0x16, 0xd3, 0x5c, 0x7a, 0x53,
	0x92, 0xc1, 0x0e, 0xb5, 0x2d, 0x57, 0x1a, 0x07, 0xfc, 0x81, 0xfa, 0x3d, 0x8b, 0x65, 0xb9, 0x49,
	0x73, 0xeb, 0xc9, 0xfe, 0xcd, 0xd3, 0x93, 0x34, 0x4f, 0x43, 0xfe, 0xc5, 0x1c, 0x13, 0x90, 0x61,
	0xf3, 0x09, 0x0a, 0x29, 0x50, 0x50, 0xa7, 0xa1, 0xd1, 0x87, 0x4d, 0xdc, 0x08, 0xde, 0x4b, 0x50,
	0x48, 0x19, 0x71, 0x57, 0x5c, 0xc1, 0x52, 0xa6, 0xcc, 0xf2, 0xad, 0x71, 0x3f, 0x6a, 0x91, 0xfa,
	0x64, 0x20, 0x21, 0xe5, 0xb8, 0xdd, 0x69, 0xb5, 0xa3, 0xd5, 0xc3, 0x12, 0x9d, 0x91, 0x7e, 0x29,
	0xd3, 0x67, 0x2e, 0x79, 0xa6, 0x98, 0xed, 0xdb, 0xe3, 0xc1, 0xe4, 0x2c, 0x30, 0x27, 0x9a, 0xfd,
	0x83, 0x65, 0xbb, 0xe0, 0x31, 0x47, 0x59, 0x45, 0x7b, 0x03, 0xbd, 0x22, 0x6e, 0x02, 0x7c, 0x03,
	0x52, 0xb1, 0x5f, 0xda, 0x7b, 0x7a, 0xec, 0x5d, 0x34, 0x72, 0xe3, 0x6c, 0x17, 0xd7, 0xf7, 0x5a,
	0x8b, 0x1c, 0x21, 0xc7, 0x97, 0xaa, 0x00, 0xd6, 0x6d, 0xee, 0x75, 0x50, 0xa2, 0x27, 0xc4, 0xc9,
	0x00, 0x13, 0xb1, 0x61, 0x8e, 0x16, 0x0d, 0x51, 0x8f, 0xf4, 0x0a, 0xa1, 0xf0, 0x81, 0x23, 0x67,
	0xae, 0x56, 0xbe, 0xb8, 0xce, 0x01, 0xb7, 0x19, 0x3c, 0x95, 0xc8, 0x7a, 0xbe, 0x35, 0xee, 0x46,
	0x2d, 0x7a, 0x33, 0x32, 0xfc, 0xde, 0x04, 0xfd, 0x4b, 0xec, 0x37, 0xa8, 0x4c, 0x5e, 0xf5, 0x2f,
	0xfd, 0x4f, 0xba, 0x3b, 0x9e, 0x96, 0x60, 0x52, 0x6a, 0x60, 0xda, 0xb9, 0xb1, 0xbc, 0x29, 0xf9,
	0x7d, 0xd8, 0xc6, 0x4f, 0xbc, 0xa3, 0x11, 0x71, 0x22, 0x50, 0x65, 0xaa, 0x5f, 0xe9, 0xbe, 0x69,
	0xb0, 0x7d, 0x25, 0x83, 0x93, 0x5b, 0xe2, 0xcc, 0x75, 0x6a, 0xf4, 0x82, 0x0c, 0xe7, 0x80, 0x0b,
	0xc4, 0xc2, 0x68, 0xf4, 0xcf, 0x51, 0xa0, 0xde, 0x70, 0x5f, 0xa8, 0xb7, 0xbd, 0x0b, 0x5e, 0xcf,
	0xe3, 0x2d, 0x26, 0xe5, 0x2a, 0x58, 0x8b, 0x2c, 0x54, 0xa9, 0x90, 0xd5, 0x75, 0xc8, 0xf3, 0xb8,
	0x4c, 0xb9, 0x8c, 0x45, 0xa8, 0xe4, 0x3a, 0xd4, 0x93, 0x63, 0xc6, 0x68, 0xe5, 0x68, 0xba, 0xfc,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xc5, 0x13, 0xfb, 0x5e, 0x02, 0x00, 0x00,
}
