// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/trending.proto

package trending

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dbba9b92d889dd, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type GithubTrendingInfo struct {
	Title                string               `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	TrendingDate         *timestamp.Timestamp `protobuf:"bytes,2,opt,name=TrendingDate,proto3" json:"TrendingDate,omitempty"`
	GitRepos             []*GitRepo           `protobuf:"bytes,3,rep,name=GitRepos,proto3" json:"GitRepos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GithubTrendingInfo) Reset()         { *m = GithubTrendingInfo{} }
func (m *GithubTrendingInfo) String() string { return proto.CompactTextString(m) }
func (*GithubTrendingInfo) ProtoMessage()    {}
func (*GithubTrendingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dbba9b92d889dd, []int{1}
}

func (m *GithubTrendingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GithubTrendingInfo.Unmarshal(m, b)
}
func (m *GithubTrendingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GithubTrendingInfo.Marshal(b, m, deterministic)
}
func (m *GithubTrendingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GithubTrendingInfo.Merge(m, src)
}
func (m *GithubTrendingInfo) XXX_Size() int {
	return xxx_messageInfo_GithubTrendingInfo.Size(m)
}
func (m *GithubTrendingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GithubTrendingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GithubTrendingInfo proto.InternalMessageInfo

func (m *GithubTrendingInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GithubTrendingInfo) GetTrendingDate() *timestamp.Timestamp {
	if m != nil {
		return m.TrendingDate
	}
	return nil
}

func (m *GithubTrendingInfo) GetGitRepos() []*GitRepo {
	if m != nil {
		return m.GitRepos
	}
	return nil
}

type GitRepo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Author               string   `protobuf:"bytes,2,opt,name=Author,proto3" json:"Author,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Href                 string   `protobuf:"bytes,4,opt,name=Href,proto3" json:"Href,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=Description,proto3" json:"Description,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=Language,proto3" json:"Language,omitempty"`
	Stars                int32    `protobuf:"varint,7,opt,name=Stars,proto3" json:"Stars,omitempty"`
	Forks                int32    `protobuf:"varint,8,opt,name=Forks,proto3" json:"Forks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitRepo) Reset()         { *m = GitRepo{} }
func (m *GitRepo) String() string { return proto.CompactTextString(m) }
func (*GitRepo) ProtoMessage()    {}
func (*GitRepo) Descriptor() ([]byte, []int) {
	return fileDescriptor_46dbba9b92d889dd, []int{2}
}

func (m *GitRepo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitRepo.Unmarshal(m, b)
}
func (m *GitRepo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitRepo.Marshal(b, m, deterministic)
}
func (m *GitRepo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitRepo.Merge(m, src)
}
func (m *GitRepo) XXX_Size() int {
	return xxx_messageInfo_GitRepo.Size(m)
}
func (m *GitRepo) XXX_DiscardUnknown() {
	xxx_messageInfo_GitRepo.DiscardUnknown(m)
}

var xxx_messageInfo_GitRepo proto.InternalMessageInfo

func (m *GitRepo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GitRepo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GitRepo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitRepo) GetHref() string {
	if m != nil {
		return m.Href
	}
	return ""
}

func (m *GitRepo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GitRepo) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *GitRepo) GetStars() int32 {
	if m != nil {
		return m.Stars
	}
	return 0
}

func (m *GitRepo) GetForks() int32 {
	if m != nil {
		return m.Forks
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "trending.Request")
	proto.RegisterType((*GithubTrendingInfo)(nil), "trending.GithubTrendingInfo")
	proto.RegisterType((*GitRepo)(nil), "trending.GitRepo")
}

func init() { proto.RegisterFile("proto/trending.proto", fileDescriptor_46dbba9b92d889dd) }

var fileDescriptor_46dbba9b92d889dd = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0x71, 0x9c, 0x3f, 0xce, 0x64, 0x59, 0x88, 0x08, 0x8b, 0x30, 0x7b, 0x30, 0x39, 0xf9,
	0xb2, 0x36, 0x64, 0x8f, 0x0b, 0x0b, 0x81, 0x50, 0x37, 0xb4, 0xf4, 0xa0, 0xe4, 0x05, 0x94, 0x78,
	0xa2, 0x98, 0xc6, 0x96, 0x6b, 0x8f, 0x0b, 0x7d, 0x94, 0x1e, 0xfa, 0x34, 0x7d, 0xb1, 0x62, 0xd9,
	0x4e, 0x93, 0x5e, 0x7b, 0x9b, 0xdf, 0x37, 0xc3, 0xa7, 0xd1, 0x37, 0x30, 0xcb, 0x0b, 0x4d, 0x3a,
	0xa4, 0x02, 0xb3, 0x38, 0xc9, 0x54, 0x60, 0x90, 0x39, 0x1d, 0xbb, 0xff, 0x54, 0x42, 0xc7, 0x6a,
	0x17, 0xec, 0x75, 0x1a, 0x2a, 0x7d, 0x92, 0x99, 0x0a, 0xcd, 0xc8, 0xae, 0x3a, 0x84, 0x39, 0xbd,
	0xe4, 0x58, 0x86, 0x94, 0xa4, 0x58, 0x92, 0x4c, 0xf3, 0xcf, 0xaa, 0xb1, 0x99, 0x8f, 0x61, 0x24,
	0xf0, 0xa9, 0xc2, 0x92, 0xe6, 0xaf, 0x16, 0xb0, 0xc8, 0x58, 0x6d, 0x5b, 0xeb, 0x75, 0x76, 0xd0,
	0x6c, 0x06, 0x83, 0x6d, 0x42, 0x27, 0xe4, 0x96, 0x67, 0xf9, 0x63, 0xd1, 0x00, 0xfb, 0x0f, 0x3f,
	0xba, 0xa9, 0x95, 0x24, 0xe4, 0x3d, 0xcf, 0xf2, 0x27, 0x0b, 0x37, 0x50, 0x5a, 0xab, 0x13, 0x06,
	0xdd, 0x02, 0xc1, 0xb6, 0x7b, 0x4f, 0x5c, 0xcd, 0xb3, 0x3f, 0xe0, 0x44, 0x09, 0x09, 0xcc, 0x75,
	0xc9, 0x6d, 0xcf, 0xf6, 0x27, 0x8b, 0x69, 0x70, 0xfe, 0x61, 0xdb, 0x11, 0xe7, 0x91, 0xf9, 0xbb,
	0x05, 0xa3, 0x16, 0xd8, 0x4f, 0xe8, 0xad, 0x63, 0xb3, 0x8d, 0x2d, 0x7a, 0xeb, 0x98, 0xfd, 0x82,
	0xe1, 0xb2, 0xa2, 0xa3, 0x2e, 0xcc, 0x12, 0x63, 0xd1, 0x12, 0x63, 0xd0, 0x7f, 0x90, 0x29, 0x72,
	0xdb, 0xa8, 0xa6, 0xae, 0xb5, 0xdb, 0x02, 0x0f, 0xbc, 0xdf, 0x68, 0x75, 0xcd, 0x3c, 0x98, 0xac,
	0xb0, 0xdc, 0x17, 0x49, 0x4e, 0x89, 0xce, 0xf8, 0xc0, 0xb4, 0x2e, 0x25, 0xe6, 0x82, 0x73, 0x2f,
	0x33, 0x55, 0x49, 0x85, 0x7c, 0x68, 0xda, 0x67, 0xae, 0xe3, 0xd9, 0x90, 0x2c, 0x4a, 0x3e, 0xf2,
	0x2c, 0x7f, 0x20, 0x1a, 0xa8, 0xd5, 0x1b, 0x5d, 0x3c, 0x96, 0xdc, 0x69, 0x54, 0x03, 0x8b, 0x37,
	0x0b, 0x9c, 0x2e, 0x05, 0xb6, 0x82, 0x69, 0x84, 0x74, 0x1d, 0x38, 0xbb, 0x08, 0xa1, 0x3d, 0x8b,
	0xfb, 0xfb, 0x2a, 0x97, 0xaf, 0xd7, 0xb9, 0x03, 0x1e, 0x21, 0x2d, 0xb3, 0x78, 0x23, 0x9f, 0xf1,
	0x9b, 0x66, 0xbb, 0xa1, 0x39, 0xdb, 0xdf, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x25, 0x80,
	0x61, 0x72, 0x02, 0x00, 0x00,
}
